### ISSUE TITLE
Does it worked in Rails 5?

### ISSUE THREAD

**Issue by smoothdvd** [Eric-Guo/where-or#12]

**Comment by bf4** [comment]
@smoothdvd this is a backport from Rails 5 to Rails 4, so it would be silly to install them together.

**Comment by ac-dc87** [comment]
no you have rails 5 for this

**Comment by Eric-Guo** [comment]
Rails 5 no need this (already support `or` in ActiveRecord), just remove this gem in your Rails 5 project.
