### ISSUE TITLE
`Relation passed to #or must be structurally compatible` fix? 

### ISSUE THREAD

**Issue by DeeWBee** [Eric-Guo/where-or#16]
Rails: 4.2.7.1
Ruby: 2.2.5p319

I have the following line 
```
return query.where(scope_hash.inject(query) { |query, (scope_name, ids)| query.or(query.public_send(scope_name, ids)) })
```

Currently I am getting `Relation passed to #or must be structurally compatible`. In doing some research, I came across https://github.com/rails/rails/issues/24055, wherein the proposed solution is https://github.com/rails/rails/issues/24055#issuecomment-228099231. When comparing `where-or.rb` to the github link, it seems the change is implemented; however, I wanted to get a second opinion. Is there anything that can be done to the gem? Or does my issue lie within my own code?

**Comment by bf4** [comment]
@DeeWBee most likely in your own code. esp since you'e not sharing what' sin scope_hash

**Comment by DeeWBee** [comment]
@bf4 It turns out my mistake was a syntax error in another location (my own fault). Thanks for the response though!
