### ISSUE TITLE
where-or breaks preloading of associations with conditions

### ISSUE THREAD

**Issue by myabc** [Eric-Guo/where-or#2]
> TypeError: Cannot visit ActiveRecord::Relation::WhereClause

See https://github.com/myabc/where-or-example and https://gist.github.com/bf4/84cff9cc6ac8489d769e#gistcomment-1593871 for a reproduction.

**Comment by oyeanuj** [comment]
I am seeing the same issue. @myabc did you find a solution to this?

**Comment by davidgeere** [comment]
Exactly the same issue here, @myabc did you ever figure this one out?

**Comment by bf4** [comment]
I just saw this.  I'm still using my patch in Rails 4.2.6 and am busy debugging other things right now ;)  but how about take a look and see if any of the source files I've listed have changed in Rails 5 since I made the patch. If not, it might be a bug in Rails 5 :)

**Comment by robmathews** [comment]
I just upgraded @myabc example to rails5 and tested it. Works fine, so I'd guess that remerging the files down would work. Here's my url - https://github.com/robmathews/where-or-example. So one of us should definitely look at the source files that have changed in the original commit, it would probably be short strokes to make the PR.

**Comment by robmathews** [comment]
Seems that the where.or! patch failed to take into account that the preloader needs to merge the AST trees.
