### ISSUE TITLE
Could you publish a new version of the gem? ie, 0.1.2

### ISSUE THREAD

**Issue by robmathews** [Eric-Guo/where-or#5]
Something like, in case your notes are too far away and you are feeling especially low on coffee:

```
gem build where-or.gemspec 
gem push where-or-0.1.2.gem
```

Thanks!

**Comment by Eric-Guo** [comment]
[0.1.2](https://rubygems.org/gems/where-or/versions/0.1.2) already pushed at the same time of #4 merged, thank your great PR.

**Comment by robmathews** [comment]
Hey thanks, I just forgot to 'bundle update where-or' myself. Senior moment ;)
